### PR TITLE
Implement zoom in and zoom out gestures. JB#45893

### PR DESCRIPTION
**Pull request by sergey-levin**
Press left ctrl to show zoom indicator, then press (and hold) left mouse
button, move mouse to change zoom.

### CODE REVIEW

**Comment by vigejolla** [comment]
I tried this but it didn't work. The indicators appear when I press the ctrl and move the mouse, but zooming does not work :(

**Comment by sergey-levin** [comment]
I tested it using maps.google.com running inside Components -> Web View. I pressed left control, then move the mouse holding left mouse button. Unfortunately, maps.google.com not working now demanding to update browser.
Please, describe how you test it.

**Comment by vigejolla** [comment]
> I tested it using maps.google.com running inside Components -> Web View. I pressed left control, then move the mouse holding left mouse button. Unfortunately, maps.google.com not working now demanding to update browser.
> Please, describe how you test it.

I tried with jolla-gallery.

**Comment by sergey-levin** [comment]
I tweaked gesture implementation a bit. It should work now.
Tested in:
- jolla-gallery
- https://www.openstreetmap.org (via Web View)
- https://osmaps.ordnancesurvey.co.uk (via Web View)

**Comment by sergey-levin** [comment]
Changed contact as suggested.

**Pull request merged**
